version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
